# Represents the commands, if any, that CodeBuild runs during the build. For example, you might use this phase to run Maven, etc.  
# © 2023 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.  
# This AWS Content is provided subject to the terms of the AWS Customer Agreement available at  
# http://aws.amazon.com/agreement or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.  

  build:
    commands:
      - python -m pytest --junitxml=pytest_reports/pytest_report.xml
      - echo Build steps are completed